name: windows_usb_printer
description: Windows 平台使用，提供 1. 搜索获取已安装驱动的打印机列表 2. 向指定打印机发送打印内容
version: 0.0.1+2
author: lixiaohong<liyufengisme@gmail.com>
homepage: https://github.com/liyufengrex/windows_usb_printer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  win32: ^4.1.1
  ffi: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.rex.windows_usb_printer
        pluginClass: WindowsUsbPrinterProvider



